### ISSUE TITLE
https access breaks the website

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/amiinmiami#14]
Browser error:

"Mixed Content: The page at 'https://amiinmiami.herokuapp.com/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://maps.googleapis.com/maps/api/geocode/json?address=9806+NE+2nd+Ave&bounds=25.25%2C-80%7C26%2C-79&sensor=false'. This request has been blocked; the content must be served over HTTPS."

If you access http://amiinmiami.herokuapp.com the website works correctly.

**Comment by Tux64** [comment]
@ErnieAtLYD Also, Stamen's tile server uses an invalid certificate over HTTPS.

**Comment by sethfitz** [comment]
From maps.stamen.com:

> If you'd like to display these map tiles on a website that requires HTTPS, use our tile SSL endpoint by replacing http://tile.stamen.com with https://stamen-tiles.a.ssl.fastly.net. Multiple subdomains can be also be used: https://stamen-tiles-{S}.a.ssl.fastly.net
> 
> If you need protocol-agnostic URLs, use //stamen-tiles-{s}.a.ssl.fastly.net/, as that endpoint will work for both SSL and non-SSL connections.

**Comment by migurski** [comment]
Thanks Seth!

**Comment by ErnieAtLYD** [comment]
Special thanks to @Tux64, @migurski and @mojodna (yay Seth long time no seeeee).

**Comment by sethfitz** [comment]
:cake:
